port: 8080
timeout: 10s

db:
  username: "postgres"
  host: "delivery-manager-db"
  port: 5432
  dbname: "postgres"
  sslmode: "disable"

jwt:
  expires: 10m
  checkHash: true

refresh-tokens:
  expires: 24h

redis:
  addr: "delivery-manager-cache"
  port: 6379
  db:
    refresh-tokens: 1